
	var easyFormCss = {
		//form
		elemBox: "tfForm-elem"
		, subjectBox: "tfForm-subject"
		, itemBox: "tfForm-item"
		, input: "tfForm-dirty tfForm-input"
		, password: "tfForm-dirty tfForm-input"
		, short: "tfForm-dirty tfForm-input tfForm-short"
		, long: "tfForm-dirty tfForm-input tfForm-long"
		, full: "tfForm-dirty tfForm-input tfForm-full"
		, submitBtn: "tfForm-submitBtn"
		, select: "tfForm-dirty tfForm-select"
		, textarea: "tfForm-dirty tfForm-textarea"
		, blog: "tfForm-dirty tfForm-blog"
		, list: "tfForm-list"
		, listSelect: "tfForm-listSelect"
		, radio: "tfForm-radio"
		//common
		, normalText: "tfForm-text"
		, smallText: "tfForm-small"
		, lightText: "tfForm-light"
		, linkText: "tfForm-link"
		, errorText: "tfForm-error"
		, btn: "tfForm-btn"
		, minibtn: "tfForm-btn tfForm-mini"
		, checkbox: "tfForm-checkbox"
		//table
		, searchBox: "tfForm-searchBox"
		, choiceBtnBox: "tfForm-choiceBtnBox"
		, filter: "tfForm-input tfForm-short tfForm-filter"
		, choice: "tfForm-choice"
		, pageRecord: "tfForm-pageRecord"
		, pageRecord: "tfForm-pageRecord"
		, pageBox: "tfForm-pageBox"
		, pageCtrl: "tfForm-pageCtrl"
		, pageNum: "tfForm-pageNum"
		, table: "tfForm-table"
		, tableThTr: "tfForm-tableThTr"
		, tableTh: "tfForm-tableTh"
		, tableTr: "tfForm-tableTr"
		, tableTd: "tfForm-tableTd"
		, img: "tfForm-img"
		, imgzoom: "tfForm-imgzoom"
	};
